### ISSUE TITLE
reloading session too often

### ISSUE THREAD

**Issue by jchris** [faunadb/dashboard#111]
Currently App.js is calling `restoreUserSession` every time the user changes the database they are browsed into. This is a heavy call, either to the website api, or to the side-effect laden `discoverKeyType` so we should only call it when the page is reloaded.

**Comment by erickpintor** [comment]
I'm testing locally and I don't see more than one call for the website. In fact, `restoreUserSession` does not call for `discoverKeyType`. That's on [clients](https://github.com/faunadb/dashboard/blob/master/src/app/clients.js#L22) store. We're not caching the already discovered keys.

**Comment by jchris** [comment]
Here is the call to restoreUserSession that looks like it is firing when the user browses between databases https://github.com/faunadb/dashboard/blob/master/src/app/App.js#L50

**Comment by erickpintor** [comment]
No, actually the like [44](https://github.com/faunadb/dashboard/blob/master/src/app/App.js#L44) is suppose to avoid the application to reach that line. `resetState` doesn't reset the logged in user.

**Comment by jchris** [comment]
I am testing using the old-school access key login, maybe when logged in using a key secret, the currentUser is null?

I just tested again and when I click a database name in the NavTree, among the requests issued by the browser are ones to create and destroy `key_type_discovery_db_created_and_deleted_automatically_always_safe_to_delete`

....

After reading the code some more I see that `discoverKeyType` is called every time `updateClients` is dispatched. It should only be called once per page load / login, since we reload the page on logout.

**Comment by jchris** [comment]
Maybe we want to move the `discoverKeyType` stuff to the authentication module? So a User object would have a rootClient that would have a type.

Maybe worth glancing at this to see the shape of the keys API in the future, before writing anything clever. https://faunadb.atlassian.net/wiki/pages/viewpage.action?pageId=12255268

**Comment by erickpintor** [comment]
For now, I think moving the keys discovery to `authentication` module will fix the problem. We can later on refactor this as we refactor the [schema tree hierarchy](https://faunadb.atlassian.net/wiki/display/SE/Schema+Tree+Hierarchy), in which we could cache the clients with their required permissions per level of the tree.
