### ISSUE TITLE
instance form fails if loaded without browsing to it

### ISSUE THREAD

**Issue by jchris** [faunadb/dashboard#35]
If you directly refresh the page when looking at class info, e.g. a URL like http://localhost:3000/db/blog_db/classes/ok - then when you submit the class form nothing happens (on master) or you get an error (on subdb-cleanup).

I think this is because the form is relying on something in its typical browse-chain to do some state thing in redux land.

**Comment by jchris** [comment]
Maybe this is a redux smell? It seems like the action -> data -> state path could be more declarative. But we aren't going to reinvent the redux wheel today.

**Comment by marrony** [comment]
I could reproduce the part `nothing happens (on master)` but not `you get an error (on subdb-cleanup)`

What is happening is that when we submit the form, we don't wait for the [promise](https://github.com/faunadb/dashboard/blob/master/src/classes/Classes.js#L127) to finish and also we don't show any information to the user that the operation finished successfully

**Comment by jchris** [comment]
Fixing https://github.com/faunadb/dashboard/issues/12 might fix this then?

**Comment by marrony** [comment]
I think we have two different issues (and instance forms) here.

One is the instance form in the class info view, where you fill a json and create a new instance.
The other is the instance preview on index info view.

I think https://github.com/faunadb/dashboard/issues/12 is talking about the instance preview right?

**Comment by jchris** [comment]
#12 was filed back when the preview and the form were more coupled. I guess let's just bring this part of #12 here:

"the instance form should disable the submit button while the query operation is in progress" just like how the schema form does it.

I feel like mucking around in that code path will make us clean up our act as far as whatever is causing this bug #35 and some related glitches I've seen but haven't figure out the full reproduction for.
