### ISSUE TITLE
use website API to get user info

### ISSUE THREAD

**Issue by jchris** [faunadb/dashboard#44]
The website should [set a cookie that the dashboard can use to make API requests](https://github.com/faunadb/website/issues/913) from the website. The API will tell the dashboard the user's account name and whether or not they have current payment information on file.

There will also be a cookie with a dashboard specific secret that can create databases, schema, and instances, etc. The UI should handle the case where that secret has been revoked in a helpful way.

**Comment by erickpintor** [comment]
This is the schema that the dashboard is currently expecting to come back from this call:

```json
{
  "endpoint": "http://localhost:8443/",
  "secret": "secret",
  "userId": "123",
  "email": "erick@faunadb.com",
  "settings": {
    "intercom": {
      "appId": "123",
      "userHash": "123"
    }
  }
}
```

**Comment by marrony** [comment]
I know by looking at the code that `userHash` is not strictly necessary in order to intercom widget shows up and also I could not find a way to retrieve that information from intercom api, so I wonder if we can drop that field?

**Comment by erickpintor** [comment]
We can not. Once you send a `userHash` for the first time, intercom will always request the `userHash`.

https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enable-secure-mode-on-your-web-product
