### ISSUE TITLE
Add a root exception handler that displays a failure message

### ISSUE THREAD

**Issue by eaceaser** [faunadb/dashboard#51]

**Comment by jchris** [comment]
There is already a [listener attached to error responses to the server](https://github.com/faunadb/dashboard/blob/master/src/container/Container.js#L76), so we could display our message in the same infrastructure. 

Also extracting that function from the Container component is probably a good idea.

**Comment by marrony** [comment]
It would be nice to have an api where we could send messages (errors or warnings) from everywhere

**Comment by erickpintor** [comment]
Yeah. I'm actually crating a notification center as part of this. I'll have a PR by tomorrow.

**Comment by erickpintor** [comment]
We can close this after https://github.com/faunadb/dashboard/pull/67 is merged.

**Comment by erickpintor** [comment]
All merged.
