### ISSUE TITLE
Clients being created every time

### ISSUE THREAD

**Issue by marrony** [faunadb/dashboard#70]
This [two lines](https://github.com/faunadb/dashboard/blob/master/src/container/Container.js#L45) are returning new clients every time `Container` is rendered. This is causing some sub-components to render unnecessarily (like `IndexQuery` that I will fix with a workaround in another issue)

**Comment by jchris** [comment]
since whatever is feeding the props to the Container knows the splat and the current user, moving the scoped client creation out of Container shouldn't have surprises.

**Comment by jchris** [comment]
Another approach could be to implement === on Clients so that they are the same if the have the same fields?

**Comment by jchris** [comment]
I think we can close this now that we've moved a lot of that stuff around
